export const LOAD_WEATHER = "LOAD_WEATHER";
export const SET_LOCATION = "SET_LOCATION";
export const LOADING = "LOADING";
export const THROW_ERROR = "THROW_ERROR";
export const ADD_TO_FAVOURITES = "ADD_TO_FAVOURITES";
export const REMOVE_FROM_FAVOURITES = "REMOVE_FROM_FAVOURITES";